name: Security veracode policy check

on:
  workflow_dispatch:
  schedule:
    - cron: "30 5 * * MON-FRI" # Every weekday at 05:35 UTC

jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    uses: ./.github/workflows/security_veracode_policy_scan_test.yml
    with:
      channel_id: ${{ vars.SLACK_CHANNEL_ID }}
    secrets:
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
