name: Security veracode pipeline check

on:
  workflow_dispatch:
  schedule:
    - cron: "35 5 * * MON-FRI" # Every weekday at 05:35 UTC

jobs:
  security-veracode-policy-check:
    name: Project security veracode policy scan
    # uses: ministryofjustice/james-typescript-test/.github/workflows/security_veracode_pipeline_scan_TEST.yml@main
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/security_veracode_pipeline_scan.yml@v1.0 #WORFKLOW VERSION
    with:
      channel_id: ${{ vars.SECURITY_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
    secrets: inherit
    