name: test git stuff

on:
  push:
    branches:
      - main  
  workflow_dispatch:
    inputs:
      previous_commit:
        description: "previous commit"
        default: '24beb8d'
        required: true
      environment:
        description: "deployment environment"
        default: 'dev'
        required: true
      namespace:
        description: "Kubernetes namespace"
        default: 'james-dev'
        required: true
      k8s_deployment_name:
        description: "Kubernetes deployment name"
        default: 'PROJECT_NAME'
        required: false
      changelog_git_paths:
        default: ""
        description: When set it will limit the file changes shown in the changelog to the specified paths only. This is useful for multi-project builds where otherwise it will show all changes from all projects.
        required: false

          
defaults:
  run:
    shell: bash

jobs:
  do_stuff:
    name: node build
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v4
    - name: find the latest deployment_name
      id: get-deployment-changelog
      shell: bash
      run:
        | 
        echo "Processing the commit history..."
        # initialise the changelog
        echo "Touching .deployment_changelog"
        touch .deployment_changelog

        CURRENT_COMMIT="${{ github.sha }}"
        PREVIOUS_COMMIT="24beb8d"
        echo "CURRENT_COMMIT=${CURRENT_COMMIT}"
        echo "PREVIOUS_COMMIT=${PREVIOUS_COMMIT}"
        # Some apps may not have set the correct k8s label with a valid app version containing a sha1

        # Check $PREVIOUS_COMMIT sha1 is valid
        echo "Running git rev-parse --quiet --verify ${PREVIOUS_COMMIT}"
        git rev-parse --quiet --verify "${PREVIOUS_COMMIT}"
        echo "Just ran git rev-parse --quiet --verify ${PREVIOUS_COMMIT}"

        if git rev-parse --quiet --verify "${PREVIOUS_COMMIT}" &>/dev/null; then
          # shellcheck disable=SC2086
          PAGER="cat" git log --oneline --no-decorate \
            --pretty=format:'%h %s (%cr)' --committer='noreply@github.com' --grep='#' \
            "${PREVIOUS_COMMIT}..${CURRENT_COMMIT}"  \
            | sed 's/Merge pull request /PR /g; s|from ministryofjustice/dependabot/|:dependabot:|g; s|from ministryofjustice/||g' \
            | tr '"' "'" | tr "\`" "'" \
            >> .deployment_changelog
        else
          echo "Changelog not available." > .deployment_changelog
        fi

        echo "DEPLOYMENT_CHANGELOG=\"$(cat .deployment_changelog)\"" >> $GITHUB_OUTPUT
